
version: 2

models:
  - name: stg_addresses
    description: "Addresses dbt model"
    columns:
      - name: address_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: stg_events
    description: "Events dbt model"
    columns:
      - name: event_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: created_at
        tests:
          - before_current_timestamp
  - name: stg_orders
    description: "Orders dbt model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: user_id
        tests:
          - relationships: 
              to: ref('stg_users')
              field: user_id          
      - name: address_id
        tests:
          - relationships: 
              to: ref('stg_addresses')
              field: address_id 
      - name: promo_id
        tests:
          - relationships: 
              to: ref('stg_promos')
              field: promo_id               
      - name: created_at
        tests: 
          - before_current_timestamp         
  - name: stg_order_items
    description: "Order items dbt model"
    columns:
      - name: surrogate_key
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id           
      - name: quantity
        tests: 
           - positive_values 
  - name: stg_products
    description: "Products dbt model"
    columns:
      - name: product_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: price
        tests: 
          - positive_values
  - name: stg_promos
    description: "Promos dbt model"
    columns:
      - name: promo_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null   
      - name: status
        tests:
          - accepted_values:
             values: ['inactive','active']                    
  - name: stg_users
    description: "Users dbt model"
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: address_id
        tests:
          - relationships: 
              to: ref('stg_addresses')
              field: address_id